name: Build and Push Docker image (disabled)

# Disabled: this workflow targeted Docker Hub and caused auth errors.
# We now publish to GHCR via ghcr-publish.yml. Keep this file for reference
# but do not trigger it automatically.
on:
  workflow_dispatch:

jobs:
  docker:
    if: false # hard-disable this job
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Disabled Docker Hub login
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Disabled Docker Hub push
      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     platforms: linux/amd64
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/veo-backend:latest

